# Generated by Django 4.1.5 on 2023-01-12 13:55

import utils
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Phone')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('P', 'Prefer not to mention'), ('M', 'Male')], default='P', max_length=1, verbose_name='Gender')),
                ('about', models.TextField(blank=True, max_length=255, null=True, verbose_name='About me')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Birthday')),
                ('avatar', models.ImageField(blank=True, default='default_avatar/default_avatar.jpg', null=True, upload_to=utils.tools.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), utils.tools.validate_size_image], verbose_name='Avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
