# Generated by Django 4.1.5 on 2023-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('P', 'Prefer not to mention'), ('F', 'Female'), ('M', 'Male')], default='P', max_length=1, verbose_name='Gender'),
        ),
    ]
