# Generated by Django 4.1.5 on 2023-01-13 01:14

import utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=utils.tools.get_path_upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mov', 'mp4'])], verbose_name='Publication')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publication',
            },
        ),
    ]
