# Generated by Django 4.1.5 on 2023-01-14 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gallery.comment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='gallery.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
